Name = input("이름을 입력하세요. : ")
number = input("학번을 입력하세요. : ")
department = input("학과를 입력하세요. : ")
univ = input("학교를 입력하세요. : ")

print("\n\n<출력>")
print("이름 : " ,Name)
print("학번 : " ,number)
print("학과 : " ,department)
print("학교 : " ,univ)